# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: "9.0.x"
  SOLUTION_PATH: "AIHR.sln"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore
    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal
